### ISSUE TITLE
Bug: Filter brings metadata into body of emitted message

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/filter-component#35]
## Steps to Reproduce
1. Create a flow: Simple Trigger -> Rest API -> Filter
  * For the REST API component, make a GET request to `https://google.com`
  * For the filter component, use the condition `0 != 1`
2. Generate a sample on the Filter component

## Expected result
* Body of produced sample is exactly the same as the sample produced by the REST API component.

## Actual Result
* Body of produced has an additional `elasticioMeta` which contains the meta information of all proceeding steps.

**Comment by shulkaolka** [comment]
Estimate includes audit vulnerabilities
