### ISSUE TITLE
Input field data in credentials cannot be evaluated as field type `JSONataView` does not work correctly for credentials  

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/filter-component#36]
**Description:** 
Input field data in credentials cannot be evaluated as field type `JSONataView` does not work correctly for credentials.
Can't be fixed from component side, requires platform fix.
**STR:**
1. create flow: 1st step (any component) -> step2 - configuration component
2. Create creds and add some input
3. Click on `Evaluate` button

**AR:**   
Value is not evalueated as this button doe not work in credentials section
![image](https://user-images.githubusercontent.com/36419533/97420341-dbf0da80-1913-11eb-8306-7b0c2786365f.png)

**ER:**
Value is evalueated.

**Comment by jhorbulyk** [comment]
Closing in favor of https://github.com/elasticio/elasticio/issues/5875
