### ISSUE TITLE
We should allow JSONata expressions in filter logic

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/filter-component#4]
`condition` should be in the in metadata instead of in the config.  This would allow JSONata inputs in the filter logic.

**Comment by drobiazko** [comment]
Now that we have content-based router, which supports JSONata expressions, this component is obsolete. Why would you use this component instead of content-based router? Because you don't know it? I believe we should deprecate this filter component and discourage our customers to us it.

**Comment by zubairov** [comment]
That's logical from our point of view, but apparently the customers who started using elastic.io _after_ both `filter` and `cbr` components were available have selected to use `filter` instead of `cbr`.
Actually in the customer's flow both `cbr` and `filter` were used which is a strong indication that we _need_ a filter component.

**Comment by drobiazko** [comment]
This is just a strong guessing. What is the true reason for using the filter component? CBR csn fo everything filter can do. We should adk this customer about the reason. Without any added value filter component should be deprecated, which does not mean it is removed.

**Comment by zubairov** [comment]
@drobiazko AFAIK we don't have neither a notion or a process or a visual support for marking components as deprecated. Feel free to ask the guys from 3S Studio (Mark) why he used Filter and not CBR.

**Comment by jhorbulyk** [comment]
My understanding of why our clients use filter and not CBR:

The client has a flow of messages travelling from component A to component B.  However, they want something that removes or blocks certain messages.  There is a word in English (in both colloquial and technical language) that describes both the action and device to remove certain elements from a flow.  That word is [filter](http://www.dictionary.com/browse/filter?s=t).  So when a client has this use case, the first solution the look for is a search for `filter`.

It is true that filtering is a special case of CBR and that we can train our users to use CBR when they want to use a filter action.  However, it is also true that numbers are a special case of bit arrays.  Just because we can remove filter and train users to use CBR instead doesn't mean we should.  Just because we have bit arrays, doesn't mean we should depricate numbers and train users in [boolean arithmetic](https://www.allaboutcircuits.com/textbook/digital/chpt-7/boolean-arithmetic/).

**Comment by drobiazko** [comment]
@jhorbulyk Thank you for sharing your thoughts on that. I see your point however I don't agree with your argumentation. We can improve the UX and make people find CBR easier, say by words like filter. Keeping filter component just because we can, is definitely not a way to go.

**Comment by jhorbulyk** [comment]
Proposed step going forward:
* Depricate the existing action in this component
* Add a new action `Simple JSONata Filter`
* There should be no config fields but the in metadata should be an object with a single boolean input.
* If that boolean is JS truthy, then the component should emit a message with empty body.
* If that boolean is JS falsey, then the component should log that the message was received but did not meet the condition.

**Comment by jhorbulyk** [comment]
PR is #6

**Comment by jhorbulyk** [comment]
**DoD**

**Component development prerequisites:**

- [ ] Development team has all needed requirements
- [ ] Access to the needed service with all needed permissions is granted
- [ ] No open tasks that could block Component development process
- [ ] The E.io’s GitHub repository must be checked if there is another implementation of the component under development. If it exists, new repository should not be created
- [ ] Component architecture should be discussed and approved before start coding

**Development:**

- [ ] Code is written and formatted in accordance with the Styling guide
- [ ] Code (incl. configs, test samples, environment variables etc.) MUST NOT contain any sensitive data like passwords, tokens, API keys etc.
- [ ] Component logs does not contain any sensitive data (credentials, input/output requests, Environment variables)
- [ ] Code is covered with unit tests
- [ ] Component code is covered with integration tests (optional)
- [ ] Triggers/actions comply with OIH patterns
- [ ] Documentation (README.md file in the Github) is 100% ready
- [ ] CI is set up
- [ ] All development branches are reviewed

**After QA:**

- [ ] All development branches are merged into master branch
- [ ] Sprint review preparation is finished (demo flow is built)

**QA:**

- [ ] Test cases for the component are ready at the TestRail
- [ ] Functional testing is finished
- [ ] Regression testing is finished (optional)
- [ ] Component is deployed to the production stage (app.elastic.io) and/or other required stage
  - Component has a proper access level
  - Smoke test is finished
- [ ] Release notes are done
- [ ] Component Roadmap is updated
- [ ] Component spreadsheet is updated

**Comment by A3a3e1** [comment]
Estimation is done in a pessimistic way as we are not sure about the current state of the task.
So the estimation assumes the whole task to be done. But likely only testing will be needed here.

**Comment by stas-fomenko** [comment]
@ZainNoor99 
Could you please add:
1. description to new and deprecated action (e.g. `this action deprecated please use...`  ) ![image](https://user-images.githubusercontent.com/36419533/58684343-9d529b80-8380-11e9-9e58-3da36d1d01b6.png)
2. some field name ![image](https://user-images.githubusercontent.com/36419533/58684487-1520c600-8381-11e9-99c6-81f38f82985e.png)

**Comment by ZainNoor99** [comment]
@stas-fomenko 
I added the descriptions to the actions however, after speaking with Jacob it seems as if it is currently not possible to add a label to the input field when using the JSONataView view class so I have left it the same.

**Comment by stas-fomenko** [comment]
@ZainNoor99 please also update action name in readme.md according to it's name in component.json - `Simple JSONata Filter`

**Comment by ZainNoor99** [comment]
@stas-fomenko 
Done
