### ISSUE TITLE
Filter Does Not Handle Passthrough Correctly

### ISSUE THREAD

**Issue by jhorbulyk** [elasticio/filter-component#8]
## Steps to Reproduce
Create the following Flow:
* Step1: Code component with code
```
// Please note only Node.js code is supported here
async function run(msg) {
	const body = { one : 'sample' };
	// You can emit as many data messages as required
	await this.emit('data', { body });
}
```
* Step2: Code component with code
```
// Please note only Node.js code is supported here
async function run(msg) {
	const body = { two : 'sample' };
	// You can emit as many data messages as required
	await this.emit('data', { body });
}
```
* Step 3: Filter with condition 
```
elasticio.step_1.body.one = two
```

## Expected Result
Filter component always emits result

## Actual result
Filter produces `The message was received but did not meet the condition.`

## Notes
[The JSONata transform component has some special code that handles this that was previously overlooked.](https://github.com/elasticio/jsonata-transform-component/blob/master/lib/actions/transform.js#L34-L45)

**Comment by ZainNoor99** [comment]
**CDoD**

**Component development prerequisites:**
 - [ ] Development team has all needed requirements
 - [ ] Access to the needed service with all needed permissions is granted
 - [ ] No open tasks that could block Component development process
 - [ ] The E.io’s GitHub repository must be checked if there is another implementation of the component under development. If it exists, new repository should not be created.
 - [ ] Component architecture should be discussed and approved before start coding
    **Development:**
- [ ] Code is written and formatted in accordance with the Styling guide
- [ ] Code (incl. configs, test samples, environment variables etc.) MUST NOT contain any sensitive data like passwords, tokens, API keys etc.
- [ ] Component logs does not contain any sensitive data (credentials, input/output requests, Environment variables)
- [ ] Code is covered with unit tests
- [ ] Component code is covered with integration tests (optional)
- [ ] Triggers/actions comply with OIH patterns
- [ ] Documentation (README.md file in the Github) is 100% ready. 
- [ ] CI is set up
- [ ] All development branches are reviewed
**After QA:**
 - [ ] All development branches are merged into master branch
 - [ ] Sprint review preparation is finished (demo flow is built)
**QA:**
- [ ] Test cases for the component are ready at the TestRail.
- [ ] Functional testing is finished.
- [ ] Regression testing is finished (optional).
- [ ] Component is deployed to the production stage (app.elastic.io) and/or other required stage.
- [ ] Component has a proper access level
- [ ] Smoke test is finished
- [ ] Release notes are done
- [ ] Component Roadmap is updated.
- [ ] Component spreadsheet is updated
